export const pages: any = [
  {
    slug: "",
    title: {
      et: "Eraklient",
      en: "Household",
      ru: "Частный клиент",
      lv: "Mājas",
      lt: "Privatiems",
    },
    segment: "household",
    frontpage: true,
  },
  {
    slug: "electricity",
    title: {
      et: "Elekter",
      en: "Electricity",
      ru: "Электричество",
      lv: "Elektrība",
      lt: "Elektra",
      pl: "Elektryczność",
    },
    segment: "household",
  },
  {
    slug: "solar",
    title: {
      et: "Päikesepaneelid",
      en: "Solar panels",
      ru: "Солнечные панели",
      lv: "Saules panelis",
      lt: "Saulės panelės",
      pl: "Panele słoneczne",
    },
    segment: "household",
  },
  {
    slug: "ari",
    title: {
      et: "Äriklient",
      en: "Business",
      ru: "Бизнес-клиент",
      lv: "Biznesam",
      lt: "Verslui",
      pl: "Biznes",
    },
    segment: "business",
    frontpage: "true",
  },
  {
    slug: "business/solar",
    title: {
      et: "Päikesepaneelid äriklientidele",
      en: "Business solar",
      ru: "Солнечные панели для бизнеса",
      lv: "Saules panelis biznesam",
      lt: "Verslo saulės panelės",
      pl: "Panele słoneczne dla biznesu",
    },
    segment: "business",
  },
  {
    slug: "business/flex",
    title: {
      et: "Paindlik energiajuhtimine",
      en: "Flexible energy management",
      ru: "Гибкое управление энергией",
      lv: "Elastīga enerģijas pārvaldība",
      lt: "Lankstus energijos valdymas",
      pl: "Elastyczne zarządzanie energią",
    },
    segment: "business",
  },
];
